### ISSUE TITLE
Installation instructions?

### ISSUE THREAD

**Issue by stevenvachon** [tarciosaraiva/zombied-chai#2]
I'm getting this error:

```
TypeError: fn is not a function
    at Object.exports.use (/project/node_modules/chai/lib/chai.js:40:5)
```

caused by:

``` js
chai.use( require("zombied-chai") );
```

**Comment by tarciosaraiva** [comment]
Hey @stevenvachon thanks for this, I will have a look as soon as I can. Cheers

**Comment by tarciosaraiva** [comment]
Hey @stevenvachon what you are doing is totally correct. The whole point behind it was related to `export default function` which exports a `default` object when you require the module thus you would need to use

```
chai.use( require("zombied-chai").default );
```

... which is bloody ugly. I fixed that now so you should be able to use it as you expected: version 1.0.69 is up.

Let me know if you run into trouble :+1:

**Comment by stevenvachon** [comment]
Works! Thanks!!
